[package]
name = "do-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
iroh = { version = "0.34.0", features = ["discovery-local-network"] }
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
