[package]
name = "do-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
iroh = { version = "0.33.0", features = ["discovery-local-network"] }
rand = "0.8.0"
tokio = { version = "1.43.0", features = ["full"] }
